# Install base apt packages
- import_tasks: roles/base/tasks/packages/steps/apt.yml
# packer
- import_tasks: roles/base/tasks/packages/steps/packer.yml
# vagrant
- import_tasks: roles/base/tasks/packages/steps/vagrant.yml
# AWS cli
- import_tasks: roles/base/tasks/packages/steps/awscli.yml
# LLVM
- import_tasks: roles/base/tasks/packages/steps/llvm.yml
# Docker
- import_tasks: roles/base/tasks/packages/steps/docker.yml
# gh cli
- import_tasks: roles/base/tasks/packages/steps/gh-cli.yml
# rr
- import_tasks: roles/base/tasks/packages/steps/rr.yml
# dyalog
#- import_tasks: roles/base/tasks/packages/steps/dyalog.yml
# nix
- import_tasks: roles/base/tasks/packages/steps/nix.yml
# conda
- import_tasks: roles/base/tasks/packages/steps/conda.yml
# Setup git
- import_tasks: roles/base/tasks/git.yml
# Fish
- import_tasks: roles/base/tasks/fish.yml
# Ptrace
- import_tasks: roles/base/tasks/ptrace.yml
# Sudoers env_keep
- import_tasks: roles/base/tasks/sudoers.yml
# Set debian_architecture
- import_tasks: roles/base/tasks/debian_arch.yml
